// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Repository;

#nullable disable

namespace ProvaPub.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20231109022344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shane Lind"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Regina Zemlak"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Miguel Rowe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marsha Prosacco"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cedric Welch"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rogelio Rolfson"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rose Hackett"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Eula Gulgowski"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Noah Leannon"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lewis Konopelski"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pamela Moore"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Mattie Kerluke"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Brett Buckridge"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Julia Willms"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Felicia Bahringer"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Marsha Kuvalis"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Alonzo Wyman"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Dewey Kihn"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Jose Haag"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Pete Kiehn"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Practical Steel Ball"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Intelligent Metal Shirt"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Generic Wooden Car"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Practical Wooden Chips"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Small Metal Bike"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Small Concrete Bike"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rustic Granite Soap"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Rustic Steel Shoes"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Incredible Fresh Gloves"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Handcrafted Metal Pants"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ergonomic Steel Chicken"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Licensed Fresh Computer"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Tasty Fresh Chicken"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ergonomic Plastic Towels"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Handmade Fresh Salad"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Handmade Granite Pants"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Gorgeous Plastic Car"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Awesome Rubber Bike"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Fantastic Metal Sausages"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Rustic Fresh Fish"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
